-- AlterTable
ALTER TABLE `USER_ACCOUNT` ADD COLUMN `STATUS` BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE `USER_MEDICINE_REGIMEN` ADD COLUMN `MEDI_LIST_ID` INTEGER NULL;

-- CreateTable
CREATE TABLE `MEDICINE_LIST` (
    `MEDI_LIST_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PROFILE_ID` INTEGER NOT NULL,
    `MEDI_ID` INTEGER NOT NULL,
    `MEDI_NICKNAME` VARCHAR(191) NULL,
    `PICTURE_OPTION` VARCHAR(191) NULL,

    PRIMARY KEY (`MEDI_LIST_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `MEDICINE_LIST` ADD CONSTRAINT `MEDICINE_LIST_PROFILE_ID_fkey` FOREIGN KEY (`PROFILE_ID`) REFERENCES `USER_PROFILE`(`PROFILE_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MEDICINE_LIST` ADD CONSTRAINT `MEDICINE_LIST_MEDI_ID_fkey` FOREIGN KEY (`MEDI_ID`) REFERENCES `MEDICINE_DATABASE`(`MEDI_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_MEDICINE_REGIMEN` ADD CONSTRAINT `USER_MEDICINE_REGIMEN_MEDI_LIST_ID_fkey` FOREIGN KEY (`MEDI_LIST_ID`) REFERENCES `MEDICINE_LIST`(`MEDI_LIST_ID`) ON DELETE SET NULL ON UPDATE CASCADE;
