-- DropForeignKey
ALTER TABLE `MEDICINE_LIST` DROP FOREIGN KEY `MEDICINE_LIST_MEDI_ID_fkey`;

-- DropIndex
DROP INDEX `MEDICINE_LIST_MEDI_ID_fkey` ON `MEDICINE_LIST`;

-- AlterTable
ALTER TABLE `MEDICINE_LIST` MODIFY `MEDI_ID` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `MEDICINE_LIST` ADD CONSTRAINT `MEDICINE_LIST_MEDI_ID_fkey` FOREIGN KEY (`MEDI_ID`) REFERENCES `MEDICINE_DATABASE`(`MEDI_ID`) ON DELETE SET NULL ON UPDATE CASCADE;
