-- CreateTable
CREATE TABLE `DEVICE_TOKEN` (
    `DEVICE_TOKEN_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TOKEN` VARCHAR(191) NOT NULL,
    `USER_ID` INTEGER NOT NULL,
    `PLATFORM` VARCHAR(191) NULL,
    `DEVICE_ID` VARCHAR(191) NULL,
    `LAST_SEEN_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `REVOKED_AT` DATETIME(3) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `DEVICE_TOKEN_TOKEN_key`(`TOKEN`),
    PRIMARY KEY (`DEVICE_TOKEN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `DEVICE_TOKEN` ADD CONSTRAINT `DEVICE_TOKEN_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
