/*
  Warnings:

  - You are about to drop the column `IS_RECEIVED` on the `MEDICATION_LOG` table. All the data in the column will be lost.
  - You are about to drop the column `MEDI_REGIMEN_ID` on the `MEDICATION_LOG` table. All the data in the column will be lost.
  - You are about to drop the column `SUPABASE_SENT_AT` on the `MEDICATION_LOG` table. All the data in the column will be lost.
  - You are about to drop the column `DELETED_AT` on the `MEDICINE_DATABASE` table. All the data in the column will be lost.
  - You are about to alter the column `MEDI_NICKNAME` on the `MEDICINE_LIST` table. The data in that column could be lost. The data in that column will be cast from `VarChar(191)` to `VarChar(25)`.
  - You are about to drop the column `DELETED_AT` on the `USER_ACCOUNT` table. All the data in the column will be lost.
  - You are about to drop the column `SUPABASE_USER_ID` on the `USER_ACCOUNT` table. All the data in the column will be lost.
  - You are about to drop the column `CYCLE_BREAK_DAYS` on the `USER_MEDICINE_REGIMEN` table. All the data in the column will be lost.
  - You are about to drop the column `CYCLE_ON_DAYS` on the `USER_MEDICINE_REGIMEN` table. All the data in the column will be lost.
  - The values [CYCLE] on the enum `USER_MEDICINE_REGIMEN_SCHEDULE_TYPE` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the column `MEAL_OFFSET_MINUTES` on the `USER_MEDICINE_REGIMEN_TIME` table. All the data in the column will be lost.
  - A unique constraint covering the columns `[PROFILE_ID,MEDI_LIST_ID,SCHEDULE_TIME]` on the table `MEDICATION_LOG` will be added. If there are existing duplicate values, this will fail.
  - Added the required column `MEDI_LIST_ID` to the `MEDICATION_LOG` table without a default value. This is not possible if the table is not empty.

*/
-- DropForeignKey
ALTER TABLE `MEDICATION_LOG` DROP FOREIGN KEY `MEDICATION_LOG_MEDI_REGIMEN_ID_fkey`;

-- DropForeignKey
ALTER TABLE `MEDICATION_LOG` DROP FOREIGN KEY `MEDICATION_LOG_PROFILE_ID_fkey`;

-- DropIndex
DROP INDEX `MEDICATION_LOG_MEDI_REGIMEN_ID_fkey` ON `MEDICATION_LOG`;

-- DropIndex
DROP INDEX `MEDICATION_LOG_PROFILE_ID_MEDI_REGIMEN_ID_SCHEDULE_TIME_key` ON `MEDICATION_LOG`;

-- DropIndex
DROP INDEX `USER_ACCOUNT_SUPABASE_USER_ID_key` ON `USER_ACCOUNT`;

-- AlterTable
ALTER TABLE `MEDICATION_LOG` DROP COLUMN `IS_RECEIVED`,
    DROP COLUMN `MEDI_REGIMEN_ID`,
    DROP COLUMN `SUPABASE_SENT_AT`,
    ADD COLUMN `DOSE` INTEGER NULL,
    ADD COLUMN `MEAL_RELATION` ENUM('BEFORE_MEAL', 'AFTER_MEAL', 'WITH_MEAL', 'NONE') NULL,
    ADD COLUMN `MEDI_LIST_ID` INTEGER NOT NULL,
    ADD COLUMN `NEXT_SNOOZE_AT` DATETIME(3) NULL,
    ADD COLUMN `UNIT` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `MEDICINE_DATABASE` DROP COLUMN `DELETED_AT`,
    ADD COLUMN `MEDI_STATUS` BOOLEAN NOT NULL DEFAULT true,
    MODIFY `MEDI_TH_NAME` VARCHAR(500) NOT NULL,
    MODIFY `MEDI_EN_NAME` VARCHAR(500) NOT NULL,
    MODIFY `MEDI_TRADE_NAME` VARCHAR(500) NULL,
    MODIFY `MEDI_USE` VARCHAR(500) NULL,
    MODIFY `MEDI_GUIDE` VARCHAR(500) NULL,
    MODIFY `MEDI_EFFECTS` VARCHAR(500) NULL,
    MODIFY `MEDI_NO_USE` VARCHAR(500) NULL,
    MODIFY `MEDI_WARNING` VARCHAR(500) NULL,
    MODIFY `MEDI_STORE` VARCHAR(500) NULL,
    MODIFY `MEDI_PICTURE` VARCHAR(500) NULL;

-- AlterTable
ALTER TABLE `MEDICINE_LIST` MODIFY `MEDI_NICKNAME` VARCHAR(25) NULL;

-- AlterTable
ALTER TABLE `USER_ACCOUNT` DROP COLUMN `DELETED_AT`,
    DROP COLUMN `SUPABASE_USER_ID`,
    ADD COLUMN `EMAIL_VERIFIED_AT` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `USER_MEDICINE_REGIMEN` DROP COLUMN `CYCLE_BREAK_DAYS`,
    DROP COLUMN `CYCLE_ON_DAYS`,
    ADD COLUMN `INTERVAL_HOUR` INTEGER NULL,
    MODIFY `SCHEDULE_TYPE` ENUM('DAILY', 'WEEKLY', 'INTERVAL') NOT NULL;

-- AlterTable
ALTER TABLE `USER_MEDICINE_REGIMEN_TIME` DROP COLUMN `MEAL_OFFSET_MINUTES`;

-- AlterTable
ALTER TABLE `USER_RELATIONSHIP` ADD COLUMN `OWNER_NICKNAME` VARCHAR(191) NULL,
    ADD COLUMN `OWNER_PICTURE` VARCHAR(191) NULL,
    ADD COLUMN `VIEWER_NICKNAME` VARCHAR(191) NULL,
    ADD COLUMN `VIEWER_PICTURE` VARCHAR(191) NULL;

-- CreateTable
CREATE TABLE `REFRESH_TOKEN` (
    `REFRESH_TOKEN_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TOKEN` VARCHAR(512) NOT NULL,
    `USER_ID` INTEGER NOT NULL,
    `EXPIRES_AT` DATETIME(3) NOT NULL,
    `REVOKED` BOOLEAN NOT NULL DEFAULT false,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `REFRESH_TOKEN_TOKEN_key`(`TOKEN`),
    PRIMARY KEY (`REFRESH_TOKEN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `VERIFICATION_TOKEN` (
    `VT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `IDENTIFIER` VARCHAR(255) NOT NULL,
    `TOKEN` VARCHAR(10) NOT NULL,
    `EXPIRES` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `VERIFICATION_TOKEN_IDENTIFIER_TOKEN_key`(`IDENTIFIER`, `TOKEN`),
    PRIMARY KEY (`VT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PASSWORD_RESET_TOKEN` (
    `PRT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TOKEN` VARCHAR(255) NOT NULL,
    `USER_ID` INTEGER NOT NULL,
    `EXPIRES_AT` DATETIME(3) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `PASSWORD_RESET_TOKEN_TOKEN_key`(`TOKEN`),
    PRIMARY KEY (`PRT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE UNIQUE INDEX `MEDICATION_LOG_PROFILE_ID_MEDI_LIST_ID_SCHEDULE_TIME_key` ON `MEDICATION_LOG`(`PROFILE_ID`, `MEDI_LIST_ID`, `SCHEDULE_TIME`);

-- AddForeignKey
ALTER TABLE `REFRESH_TOKEN` ADD CONSTRAINT `REFRESH_TOKEN_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PASSWORD_RESET_TOKEN` ADD CONSTRAINT `PASSWORD_RESET_TOKEN_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MEDICATION_LOG` ADD CONSTRAINT `MEDICATION_LOG_MEDI_LIST_ID_fkey` FOREIGN KEY (`MEDI_LIST_ID`) REFERENCES `MEDICINE_LIST`(`MEDI_LIST_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
