/*
  Warnings:

  - You are about to drop the `User` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE `User`;

-- CreateTable
CREATE TABLE `USER_ACCOUNT` (
    `USER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_EMAIL` VARCHAR(191) NOT NULL,
    `USER_PASSWORD` VARCHAR(191) NOT NULL,
    `LAST_LOGIN` DATETIME(3) NULL,
    `CREATE_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DELETED_AT` DATETIME(3) NULL,
    `UPDATE_AT` DATETIME(3) NOT NULL,
    `TUTORIAL_DONE` BOOLEAN NOT NULL DEFAULT false,
    `ROLE` ENUM('SuperAdmin', 'Admin', 'User') NOT NULL DEFAULT 'User',

    UNIQUE INDEX `USER_ACCOUNT_USER_EMAIL_key`(`USER_EMAIL`),
    PRIMARY KEY (`USER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_PROFILE` (
    `PROFILE_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NOT NULL,
    `PROFILE_NAME` VARCHAR(191) NOT NULL,
    `PROFILE_PICTURE` VARCHAR(191) NULL,

    PRIMARY KEY (`PROFILE_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MEDICINE_DATABASE` (
    `MEDI_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `MEDI_TH_NAME` VARCHAR(191) NOT NULL,
    `MEDI_EN_NAME` VARCHAR(191) NOT NULL,
    `MEDI_TRADE_NAME` VARCHAR(191) NULL,
    `MEDI_TYPE` ENUM('ORAL', 'TOPICAL') NOT NULL,
    `MEDI_USE` VARCHAR(191) NULL,
    `MEDI_GUIDE` VARCHAR(191) NULL,
    `MEDI_EFFECTS` VARCHAR(191) NULL,
    `MEDI_NO_USE` VARCHAR(191) NULL,
    `MEDI_WARNING` VARCHAR(191) NULL,
    `MEDI_STORE` VARCHAR(191) NULL,
    `MEDI_PICTURE` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATE_AT` DATETIME(3) NOT NULL,
    `DELETED_AT` DATETIME(3) NULL,
    `ADMIN_ID` INTEGER NULL,

    PRIMARY KEY (`MEDI_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_REQUEST` (
    `REQUEST_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USER_ID` INTEGER NOT NULL,
    `REQUEST_TYPE` ENUM('PROBLEM', 'HELP', 'IMPROVEMENT', 'ADD_MEDICINE') NOT NULL,
    `REQUEST_TITLE` VARCHAR(191) NOT NULL,
    `REQUEST_DETAILS` VARCHAR(191) NOT NULL,
    `STATUS` ENUM('PENDING', 'REJECTED', 'DONE') NOT NULL DEFAULT 'PENDING',
    `ADMIN_ID` INTEGER NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,
    `PICTURE` VARCHAR(191) NULL,

    PRIMARY KEY (`REQUEST_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_RELATIONSHIP` (
    `RELATIONSHIP_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `OWNER_USER_ID` INTEGER NOT NULL,
    `VIEWER_USER_ID` INTEGER NOT NULL,
    `IS_RECEIVER_EMAIL` VARCHAR(191) NOT NULL,
    `PROFILE_IDS` JSON NULL,
    `STATUS` ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`RELATIONSHIP_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `MEDICATION_LOG` (
    `LOG_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PROFILE_ID` INTEGER NOT NULL,
    `MEDI_REGIMEN_ID` INTEGER NOT NULL,
    `SCHEDULE_TIME` DATETIME(3) NOT NULL,
    `IS_RECEIVED` BOOLEAN NOT NULL,
    `RESPONSE_STATUS` ENUM('TAKE', 'SKIP', 'SNOOZ') NULL,
    `RESPONSE_AT` DATETIME(3) NULL,
    `SNOOZED_COUNT` INTEGER NULL,
    `NOTE` VARCHAR(191) NULL,

    PRIMARY KEY (`LOG_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_MEDICINE_REGIMEN` (
    `MEDI_REGIMEN_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PROFILE_ID` INTEGER NOT NULL,
    `MEDI_ID` INTEGER NOT NULL,
    `MEDI_NICKNAME` VARCHAR(191) NULL,
    `SCHEDULE_TYPE` ENUM('DAILY', 'WEEKLY', 'INTERVAL', 'CYCLE') NOT NULL,
    `START_DATE` DATETIME(3) NOT NULL,
    `END_DATE` DATETIME(3) NULL,
    `DAYS_OF_WEEK` VARCHAR(191) NULL,
    `INTERVAL_DAYS` INTEGER NULL,
    `NEXT_OCCURRENCE_AT` DATETIME(3) NULL,
    `CYCLE_ON_DAYS` INTEGER NULL,
    `CYCLE_BREAK_DAYS` INTEGER NULL,
    `CYCLE_ANCHOR_DATE` DATETIME(3) NULL,
    `PICTURE_OPTION` VARCHAR(191) NULL,

    PRIMARY KEY (`MEDI_REGIMEN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_MEDICINE_REGIMEN_TIME` (
    `TIME_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `MEDI_REGIMEN_ID` INTEGER NOT NULL,
    `TIME` DATETIME(3) NOT NULL,
    `DOSE` INTEGER NOT NULL,
    `UNIT` VARCHAR(191) NOT NULL,
    `MEAL_RELATION` ENUM('BEFORE_MEAL', 'AFTER_MEAL', 'WITH_MEAL', 'NONE') NOT NULL,
    `MEAL_OFFSET_MINUTES` INTEGER NULL,

    PRIMARY KEY (`TIME_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `USER_PROFILE` ADD CONSTRAINT `USER_PROFILE_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_REQUEST` ADD CONSTRAINT `USER_REQUEST_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_REQUEST` ADD CONSTRAINT `USER_REQUEST_ADMIN_ID_fkey` FOREIGN KEY (`ADMIN_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_RELATIONSHIP` ADD CONSTRAINT `USER_RELATIONSHIP_OWNER_USER_ID_fkey` FOREIGN KEY (`OWNER_USER_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_RELATIONSHIP` ADD CONSTRAINT `USER_RELATIONSHIP_VIEWER_USER_ID_fkey` FOREIGN KEY (`VIEWER_USER_ID`) REFERENCES `USER_ACCOUNT`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MEDICATION_LOG` ADD CONSTRAINT `MEDICATION_LOG_PROFILE_ID_fkey` FOREIGN KEY (`PROFILE_ID`) REFERENCES `USER_PROFILE`(`PROFILE_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MEDICATION_LOG` ADD CONSTRAINT `MEDICATION_LOG_MEDI_REGIMEN_ID_fkey` FOREIGN KEY (`MEDI_REGIMEN_ID`) REFERENCES `USER_MEDICINE_REGIMEN`(`MEDI_REGIMEN_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_MEDICINE_REGIMEN` ADD CONSTRAINT `USER_MEDICINE_REGIMEN_PROFILE_ID_fkey` FOREIGN KEY (`PROFILE_ID`) REFERENCES `USER_PROFILE`(`PROFILE_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_MEDICINE_REGIMEN` ADD CONSTRAINT `USER_MEDICINE_REGIMEN_MEDI_ID_fkey` FOREIGN KEY (`MEDI_ID`) REFERENCES `MEDICINE_DATABASE`(`MEDI_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `USER_MEDICINE_REGIMEN_TIME` ADD CONSTRAINT `USER_MEDICINE_REGIMEN_TIME_MEDI_REGIMEN_ID_fkey` FOREIGN KEY (`MEDI_REGIMEN_ID`) REFERENCES `USER_MEDICINE_REGIMEN`(`MEDI_REGIMEN_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
